version: "3.3"
services:
  nginx:
    image: nginx:1.15.5
    restart: always
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./www:/usr/share/nginx/html:ro
      - ./logs:/var/log/nginx
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf/conf.d:/etc/nginx/conf.d
  mysql:
    image: mysql:5.7.23
    restart: always
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./conf/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro
      - ./mysql/:/var/lib/mysql/:rw
    environment:
      MYSQL_USER: sangoes
      MYSQL_PASSWORD: "Sangoes123456"
      MYSQL_ROOT_PASSWORD: "Sangoes123456"
  redis:
    image: redis:4.0.11
    restart: always
    container_name: redis
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data
      - ./conf/redis.conf:/usr/local/etc/redis/redis.conf
  rabbit:
    image: rabbitmq:management
    hostname: rabbit
    restart: always
    container_name: rabbit
    ports:
      - "4369:4369"
      - "5671:5671"
      - "5672:5672"
      - "15671:15671"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=sangoes
      - RABBITMQ_DEFAULT_PASS=Sangoes123456
  wordpress:
        image: wordpress:latest
        hostname: wordpress
        restart: always
        container_name: wordpress
        ports:
          - "8282:80"
        environment:
            - WORDPRESS_DB_HOST=mysql
            - WORDPRESS_DB_USER=root
            - WORDPRESS_DB_PASSWORD=root
            - WORDPRESS_DB_NAME=xbclub
            - WORDPRESS_TABLE_PREFIX=wp_
        volumes:
            - ./www:/var/www/html:rw
            - ./php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini:ro
            - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
